_.setTranslation({
  "Dropbox connection": "Dropbox connection", // nepoužije se
  "connect game to dropbox local storage": "connect game to dropbox local storage", // nepoužije se
  "connect": "připoj",
  "cancel": "zruš",
  "Dropbox Export / Import": "Dropbox Export / Import",
  "export or import save data to dropbox datastorage": "export or import save data to dropbox datastorage",
  "your are connected to dropbox with account / email ": "your are connected to dropbox with account / email ",
  "save": "ulož",
  "load": "nahraj",
  "signout": "odhlaš se",
  "choose one slot to save to": "choose one slot to save to",
  "save to slot": "save to slot",
  "choose one slot to load from": "choose one slot to load from",
  "load from slot": "load from slot",
  "successfully saved to dropbox datastorage": "successfully saved to dropbox datastorage",
  "error while saving to dropbox datastorage": "error while saving to dropbox datastorage",
  "ok": "ok",
  "boxer": "boxer",
  "punches do more damage": "údery jsou účinnější",
  "learned to throw punches with purpose": "naučeno jak udeřit účelně",
  "martial artist": "znalec válčení",
  "punches do even more damage.": "údery jsou ještě účinnější.",
  "learned to fight quite effectively without weapons": "naučen efektivnější boj beze zbraní",
  "unarmed master": "neozbrojený mistr",
  "punch twice as fast, and with even more force": "údery dvakrát rychlejší a s ještě větší silou",
  "learned to strike faster without weapons": "naučeno rozdávat údery beze zbraní rychleji",
  "barbarian": "divoch",
  "melee weapons deal more damage": "kontaktní zbraně jsou účinnější",
  "learned to swing weapons with force": "naučeno máchání zbraněmi s větší silou",
  "slow metabolism": "zpomal trávení",
  "go twice as far without eating": "dojdi dvakrát dál bez jídla",
  "learned how to ignore the hunger": "naučeno jak překonat hlad",
  "desert rat": "pouštní krysa",
  "go twice as far without drinking": "dojdi dvakrát dál bez vody",
  "learned to love the dry air": "naučeno snášet lépe suchý vzduch",
  "evasive": "krytí",
  "dodge attacks more effectively": "uhýbej útokům účinněji",
  "learned to be where they're not": "naučeno jak se lépe krýt",
  "precise": "přesnost",
  "land blows more often": "trefy budou častější",
  "learned to predict their movement": "naučeno jak předvídat cizí pohyby",
  "scout": "zvěd",
  "see farther": "dohlédni dál",
  "learned to look ahead": "naučeno předvídat",
  "stealthy": "nenápadnost",
  "better avoid conflict in the wild": "lépe se vyhýbej konfliktům v divočině",
  "learned how not to be seen": "naučeno jak nebýt spatřen",
  "gastronome": "gastronom",
  "restore more health when eating": "obnov více zdraví z potravy",
  "learned to make the most of food": "naučeno jak získat z potravy co nejvíce",
  "get the app.": "získej aplikaci.",
  "lights off.": "zhasni.",
  "hyper.": "hyper.",
  "restart.": "restart.",
  "share.": "sdílej.",
  "save.": "ulož.",
  "dropbox.": "dropbox.",
  "github.": "github.",
  "Export / Import": "Export / Import",
  "export or import save data, for backing up": "export or import save data, for backing up",
  "or migrating computers": "or migrating computers",
  "export": "export",
  "import": "import",
  "save this.": "save this.",
  "got it": "got it",
  "are you sure?": "are you sure?",
  "if the code is invalid, all data will be lost.": "if the code is invalid, all data will be lost.",
  "this is irreversible.": "this is irreversible.",
  "yes": "ano",
  "no": "ne",
  "put the save code here.": "put the save code here.",
  "Restart?": "Restart?",
  "restart the game?": "restartovat hru?",
  "Get the App": "Získej aplikaci",
  "bring the room with you.": "vem si místnost sebou.",
  "ios": "ios",
  "android": "android",
  "Share": "Sdílej",
  "bring your friends.": "přiveď přátele.",
  "facebook": "facebook",
  "google+": "google+",
  "twitter": "twitter",
  "reddit": "reddit",
  "close": "zavři",
  "lights on.": "rozsviť.",
  "Go Hyper?": "Zapnout Hyper?",
  "classic.": "klasický.",
  "{0} per {1}s": "{0} za {1}s",
  "pause.": "pauza.",
  "eat meat": "sněz maso",
  "use meds": "spolkni lék",
  "miss": "minul",
  "stunned": "omráčený",
  "stun": "omrač",
  "leave": "jdi pryč",
  "drop:": "polož:",
  "nothing": "nic",
  "take": "seber",
  "take:": "seber:",
  "nothing to take": "nic k sebrání",
  "all": "vše",
  "take everything": "seber všechno",
  "take all you can": "seber vše co můžeš",
  " and ": " a ",
  "*** EVENT ***": "*** UDÁLOST ***",
  "A Snarling Beast": "Vyjící šelma",
  "snarling beast": "vyjící šelma",
  "the snarling beast is dead": "vyjící šelma je mrtvá",
  "a snarling beast leaps out of the underbrush": "vyjící šelma vyskočila z lesního podrostu",
  "A Gaunt Man": "Vychrtlý muž",
  "gaunt man": "vychrtlý muž",
  "the gaunt man is dead": "vychrtlý muž je mrtev",
  "a gaunt man approaches, a crazed look in his eye": "vychrtlý muž se přiblížil, v očích výraz šílenství",
  "A Strange Bird": "Podivný pták",
  "strange bird": "podivný pták",
  "the strange bird is dead": "podivný pták je mrtev",
  "a strange looking bird speeds across the plains": "podivně vypadající pták se rychle blíží přes planinu",
  "A Shivering Man": "Třesoucí se muž",
  "shivering man": "třesoucí se muž",
  "the shivering man is dead": "třesoucí se muž je mrtev",
  "a shivering man approaches and attacks with surprising strength": "třesoucí se muž přistoupil a zaútočil s překvapivou silou",
  "A Man-Eater": "Člověkožrout",
  "man-eater": "člověkožrout",
  "the man-eater is dead": "člověkožrout je mrtev",
  "a large creature attacks, claws freshly bloodied": "velká obluda útočí, pařáty čerstvě od krve",
  "A Scavenger": "Mrchožrout",
  "scavenger": "mrchožrout",
  "the scavenger is dead": "mrchožrout je mrtev",
  "a scavenger draws close, hoping for an easy score": "mrchožrout se přiblížil, doufaje ve snadnou kořist",
  "A Huge Lizard": "Obrovský ještěr",
  "lizard": "ještěr",
  "the lizard is dead": "ještěr je mrtev",
  "the grass thrashes wildly as a huge lizard pushes through": "tráva se divoce vlní jak se jí prodírá obrovský ještěr",
  "A Feral Terror": "Divoký děs",
  "feral terror": "divoký děs",
  "the feral terror is dead": "divoký děs je mrtev",
  "a beast, wilder than imagining, erupts out of the foliage": "příšera divočejší, než si lze představit, vyrazila z listoví",
  "A Soldier": "Voják",
  "soldier": "voják",
  "the soldier is dead": "voják je mrtev",
  "a soldier opens fire from across the desert": "voják zahájil palbu z opačné strany pouště",
  "A Sniper": "Odstřelovač",
  "sniper": "odstřelovač",
  "the sniper is dead": "odstřelovač je mrtev",
  "a shot rings out, from somewhere in the long grass": "střely sviští odněkud z vysoké trávy",
  "The Thief": "Zloděj",
  "the villagers haul a filthy man out of the store room.": "vesničané vyvlekli ze skladiště špinavého muže.",
  "say his folk have been skimming the supplies.": "říkají, že jeho lidé kradli zásoby.",
  "say he should be strung up as an example.": "říkají, že by měl být pověšen pro výstrahu.",
  "a thief is caught": "zloděj je polapen",
  "hang him": "pověs ho",
  "spare him": "ušetři ho",
  "the villagers hang the thief high in front of the store room.": "vesničané pověsili zloděje před skladištěm.",
  "the man says he's grateful. says he won't come around any more.": "muž říká, že je vděčný a že už sem ani nepáchne.",
  "shares what he knows about sneaking before he goes.": "podělí se o to, co ví o plížení, dříve než odejde.",
  "A Ruined Trap": "Rozbitá past",
  "some of the traps have been torn apart.": "pár pastí bylo částečně rozerváno.",
  "large prints lead away, into the forest.": "velké stopy vedou pryč do lesa.",
  "some traps have been destroyed": "pár pastí bylo zničeno",
  "track them": "sleduj je",
  "ignore them": "ignoruj je",
  "the tracks disappear after just a few minutes.": "po pár minutách se stopy ztratily.",
  "the forest is silent.": "les je tichý.",
  "nothing was found": "nic nebylo nalezeno",
  "go home": "jdi domů",
  "not far from the village lies a large beast, its fur matted with blood.": "nedaleko vesnice leží velká šelma, její srst je slepená krví.",
  "it puts up little resistance before the knife.": "kladla noži malý odpor.",
  "there was a beast. it's dead now": "byla tu šelma. nyní je mrtvá",
  "Fire": "Oheň",
  "a fire rampages through one of the huts, destroying it.": "oheň řádí v jedné z chýší, lehla popelem.",
  "all residents in the hut perished in the fire.": "všichni obyvatelé chýše zahynuli v plamenech.",
  "a fire has started": "oheň se rozhořel",
  "mourn": "truchli",
  "some villagers have died": "pár vesničanů zahynulo",
  "Sickness": "Nemoc",
  "a sickness is spreading through the village.": "choroba se šíří vesnicí.",
  "medicine is needed immediately.": "léky jsou potřeba okamžitě.",
  "some villagers are ill": "někteří vesničané jsou nemocní",
  "1 medicine": "1 lék",
  "ignore it": "ignoruj to",
  "the sickness is cured in time.": "nemoc byla vyléčena včas.",
  "sufferers are healed": "nemocní jsou léčeni",
  "the sickness spreads through the village.": "choroba se šíří vesnicí.",
  "the days are spent with burials.": "pohřby se staly nápní dnů.",
  "the nights are rent with screams.": "noci jsou naplněny nářkem.",
  "sufferers are left to die": "nemocní jsou ponecháni umírání",
  "Plague": "Mor",
  "a terrible plague is fast spreading through the village.": "hrozná epidemie moru se rychle šíří vesnicí.",
  "a plague afflicts the village": "mor zachvátil vesnici",
  "buy medicine": "kup léky",
  "5 medicine": "5 léků",
  "do nothing": "nedělej nic",
  "the plague is kept from spreading.": "moru bylo zabráněno v šíření.",
  "only a few die.": "pouze pár lidí zemřelo.",
  "the rest bury them.": "ostatní je pohřbili.",
  "epidemic is eradicated eventually": "choroba je konečně vymýcena",
  "the plague rips through the village.": "mor vtrhl do vesnice.",
  "the only hope is a quick death.": "jedinou nadějí je rychlá smrt.",
  "population is almost exterminated": "populace je téměř vyhlazena",
  "A Beast Attack": "Útok šelmy",
  "a pack of snarling beasts pours out of the trees.": "tlupa vyjících šelem se spustila ze stromů.",
  "the fight is short and bloody, but the beasts are repelled.": "boj je krátký a krvavý, ale šelmy jsou zahnány.",
  "the villagers retreat to mourn the dead.": "vesničané se stáhli, aby oplakávali mrtvé.",
  "wild beasts attack the villagers": "divoké šelmy útočí na vesničany",
  "predators become prey. price is unfair": "z lovců se stala kořist. cena je nespravedlivá",
  "A Military Raid": "Vojenský přepad",
  "a gunshot rings through the trees.": "kulka zasvištěla mezi stromy.",
  "well armed men charge out of the forest, firing into the crowd.": "dobře vyzbrojení muži se vynořili z lesa a pálí do osadníků.",
  "after a skirmish they are driven away, but not without losses.": "po potyčce byli zahnáni, ale nikoliv beze ztrát.",
  "troops storm the village": "vojsko decimuje vesnici",
  "warfare is bloodthirsty": "válka je krvavá",
  "The Nomad": "Kočovník",
  "won't say from where he came, but it's clear that he's not staying.": "neřekne odkud přišel, ale je jasné, že nezůstane.",
  "a nomad arrives, looking to trade": "kočovník dorazil za účelem obchodu",
  "buy scales": "kup šupiny",
  "buy teeth": "kup zuby",
  "buy bait": "kup návnadu",
  "traps are more effective with bait.": "pasti jsou účinnější s návnadou.",
  "buy compass": "kup kompas",
  "the old compass is dented and dusty, but it looks to work.": "starý kompas je promáčknutý a zaprášený, ale vypadá funkčně.",
  "say goodbye": "rozluč se",
  "Noises": "Zvuky",
  "through the walls, shuffling noises can be heard.": "skrze zdi je slyšet šouravé zvuky.",
  "can't tell what they're up to.": "těžko říct čím jsou způsobeny.",
  "strange noises can be heard through the walls": "skrze zdi je slyšet divné zvuky",
  "investigate": "prozkoumej",
  "vague shapes move, just out of sight.": "nejasné obrysy se mihly pryč z dohledu.",
  "the sounds stop.": "zvuky ustaly.",
  "go back inside": "vrať se dovnitř",
  "the night is silent.": "noc je tichá.",
  "scratching noises can be heard from the store room.": "ze skladiště jsou slyšet škrábavé zvuky.",
  "something's in there.": "něco tam je.",
  "something's in the store room": "něco je ve skladišti",
  "some wood is missing.": "nějaké dřevo chybí.",
  "the ground is littered with small scales": "zem je pokryta malými šupinami",
  "the ground is littered with small teeth": "zem je pokryta malými zuby",
  "the ground is littered with scraps of cloth": "zem je pokryta útržky plátna",
  "The Beggar": "Žebrák",
  "a beggar arrives.": "dorazil žebrák.",
  "asks for any spare furs to keep him warm at night.": "prosí o nějaké kožešiny aby se mohl v noci zahřát.",
  "a beggar arrives": "dorazil žebrák",
  "give 50": "dej 50",
  "give 100": "dej 100",
  "turn him away": "pošli ho pryč",
  "the beggar expresses his thanks.": "žebrák projevil svůj vděk.",
  "leaves a pile of small scales behind.": "zanechal po sobě kupku malých šupin.",
  "leaves a pile of small teeth behind.": "zanechal po sobě kupku malých zubů.",
  "leaves some scraps of cloth behind.": "zanechal po sobě pár útržků plátna.",
  "The Mysterious Wanderer": "Tajemný tulák",
  "builder's not sure he's to be trusted.": "stavitel si není jist zda mu může důvěřovat.",
  "a mysterious wanderer arrives": "dorazil tajemný tulák",
  "give 500": "dej 500",
  "the wanderer leaves, cart loaded with wood": "tulák odešel s vozíkem s nákladem dřeva",
  "the mysterious wanderer returns, cart piled high with wood.": "tajemný tulák se vrátil s vozíkem plně napěchovaným dřevem.",
  "builder's not sure she's to be trusted.": "stavitel si není jist zda mu může důvěřovat.",
  "turn her away": "pošli ho pryč",
  "the wanderer leaves, cart loaded with furs": "tulák odešel s vozíkem s nákladem kožešiny",
  "the mysterious wanderer returns, cart piled high with furs.": "tajemný tulák se vrátil s vozíkem plně napěchovaným kožešinami.",
  "The Scout": "Zvěd",
  "the scout says she's been all over.": "zvěd říká, že byl všude okolo.",
  "willing to talk about it, for a price.": "je ochoten o tom mluvit, ale zadarmo to nebude.",
  "a scout stops for the night": "zvěd se zastavil na přenocování",
  "buy map": "kup mapu",
  "the map uncovers a bit of the world": "mapa odkrývá kousek světa",
  "learn scouting": "pouč se od zvěda",
  "The Master": "Mudrc",
  "an old wanderer arrives.": "dorazil starý tulák.",
  "he smiles warmly and asks for lodgings for the night.": "mile se usmívá a žádá o ubytování na noc.",
  "an old wanderer arrives": "dorazil starý tulák",
  "agree": "souhlas",
  "in exchange, the wanderer offers his wisdom.": "na oplátku tulák nabízí svoji moudrost.",
  "evasion": "uhýbání",
  "precision": "přesnost",
  "force": "síla",
  "The Sick Man": "Nemocný muž",
  "a man hobbles up, coughing.": "muž kulhá a kašle.",
  "he begs for medicine.": "žebrá o léky.",
  "a sick man hobbles up": "přikulhal se nemocný muž",
  "give 1 medicine": "dej 1 lék",
  "the man swallows the medicine eagerly": "muž dychtivě spolkl lék",
  "tell him to leave": "pošli ho pryč",
  "the man is thankful.": "muž je vděčný.",
  "he leaves a reward.": "odměnil se.",
  "some weird metal he picked up on his travels.": "nějaký zvláštní kov co sebral na svých cestách.",
  "some weird glowing boxes he picked up on his travels.": "nějaké zvláštní teplé schránky co sebral na svých cestách.",
  "all he has are some scales.": "vše co má je pár šupin.",
  "the man expresses his thanks and hobbles off.": "muž vyjádřil svoji vděčnost a odbelhal se.",
  "An Outpost": "Základna",
  "a safe place in the wilds.": "bezpečné místo v divočině.",
  "A Murky Swamp": "Kalná bažina",
  "rotting reeds rise out of the swampy earth.": "zahnívající rákosí ční z bažinaté země.",
  "a lone frog sits in the muck, silently.": "osamělá žába sedí tiše v bahně.",
  "a swamp festers in the stagnant air.": "bažina čpí v nehybném vzduchu.",
  "enter": "vstup",
  "deep in the swamp is a moss-covered cabin.": "hluboko v bažině je mechem porostlá chatrč.",
  "an old wanderer sits inside, in a seeming trance.": "starý tulák sedí uvnitř, ve zdánlivém transu.",
  "talk": "mluv",
  "the wanderer takes the charm and nods slowly.": "tulák si bere talisman a pomalu pokyvuje hlavou.",
  "he speaks of once leading the great fleets to fresh worlds.": "říká, že kdysi vedl velkou flotilu k novým světům.",
  "unfathomable destruction to fuel wanderer hungers.": "nepochopitelné ničení naplňovalo tulákovu dychtivost.",
  "his time here, now, is his penance.": "jeho čas zde je nyní jeho pokáním.",
  "A Damp Cave": "Vlhká jeskyně",
  "the mouth of the cave is wide and dark.": "ústí jeskyně je široké a temné.",
  "can't see what's inside.": "nelze spatřit co je vevnitř.",
  "the earth here is split, as if bearing an ancient wound": "země je zde rozťatá, jako by utrpěla dávné zranění",
  "go inside": "jdi dovnitř",
  "a startled beast defends its home": "vylekaná šelma brání své doupě",
  "continue": "pokračuj",
  "leave cave": "opusť jeskyni",
  "the cave narrows a few feet in.": "jeskyně se po pár metrech zužuje.",
  "the walls are moist and moss-covered": "stěny jsou vlhké a porostlé mechem",
  "squeeze": "vmáčkni se dovnitř",
  "the remains of an old camp sits just inside the cave.": "uvnitř jeskyně se rozprostírají zbytky starého tábořiště.",
  "bedrolls, torn and blackened, lay beneath a thin layer of dust.": "přikrývky, roztrhané a zčernalé, leží pod slabou vrstvou prachu.",
  "the body of a wanderer lies in a small cavern.": "tělo tuláka leží v malé kaverně.",
  "rot's been to work on it, and some of the pieces are missing.": "rozklad na něm zapracoval a některé části chybí.",
  "can't tell what left it here.": "těžko říct co ho zde zanechalo.",
  "the torch sputters and dies in the damp air": "pochodeň zaprskala a zhasla ve vlhkém vzduchu",
  "the darkness is absolute": "černočerná tma",
  "the torch goes out": "pochodeň vyhořela",
  "a cave lizard attacks": "jeskynní ještěr útočí",
  "a large beast charges out of the dark": "obrovská šelma se vynořila ze tmy",
  "a giant lizard shambles forward": "obří ještěr se šourá proti tobě",
  "the nest of a large animal lies at the back of the cave.": "doupě velkého zvířete leží v zadní části jeskyně.",
  "a small supply cache is hidden at the back of the cave.": "malá zásobárna je skryta v zadní části jeskyně.",
  "an old case is wedged behind a rock, covered in a thick layer of dust.": "stará schránka je zaklíněna za kamenem, pokryta silnou vrstvou prachu.",
  "A Deserted Town": "Opuštěné město",
  "a small suburb lays ahead, empty houses scorched and peeling.": "malé předměstí v dohledu, prázdné domy sežehnuté a oprýskané.",
  "the town lies abandoned, its citizens long dead": "město je opuštěno, jeho obyvatelé dávno mrtvi",
  "explore": "prozkoumej",
  "the double doors creak endlessly in the wind.": "dvoukřídlé dveře bez ustání skřípou ve větru.",
  "leave town": "opusť město",
  "ambushed on the street.": "přepaden na ulici.",
  "a squat building up ahead.": "vybydlená budova v dohledu.",
  "a green cross barely visible behind grimy windows.": "zelený kříž sotva viditelný za špinavým okny.",
  "a small cache of supplies is tucked inside a rusting locker.": "malá schránka se zásobami je schována v rezavějící skříňce.",
  "a scavenger waits just inside the door.": "mrchožrout číhá hned za dveřmi.",
  "a beast stands alone in an overgrown park.": "bestie stojí osamocena v přerostlém parku.",
  "an overturned caravan is spread across the pockmarked street.": "převrácená maringotka přehrazuje ulici plnou výmolů.",
  "a madman attacks, screeching.": "vřeštící šílenec útočí.",
  "a thug moves out of the shadows.": "pobuda se vynořil ze stínu.",
  "a beast charges out of a ransacked classroom.": "obluda se vyřítila z vypleněné třídy.",
  "through the large gymnasium doors, footsteps can be heard.": "za velkými dveřmi do tělocvičny je slyšet kroky.",
  "the torchlight casts a flickering glow down the hallway.": "světlo pochodně vrhá mihotavou záři dolů do chodby.",
  "the footsteps stop.": "kroky ustaly.",
  "another beast, draw by the noise, leaps out of a copse of trees.": "další obluda, přilákána hlukem, vyskočila z mladého lesa.",
  "something's causing a commotion a ways down the road.": "cosi způsobuje rozruch dole na ulici.",
  "a fight, maybe.": "boj, asi.",
  "can't read the words.": "nelze přečíst slova.",
  "a panicked scavenger bursts through the door, screaming.": "vyděšený ječící mrchožrout se vyřítil ze dveří.",
  "a man stands over a dead wanderer. notices he's not alone.": "muž stojí nad mrtvým tulákem. povšiml si, že není sám.",
  "scavenger had a small camp in the school.": "mrchožrout měl malé tábořiště ve škole.",
  "collected scraps spread across the floor like they fell from heaven.": "nashromážděné zbytky jsou rozprostřeny po podlaze jako by spadly z nebe.",
  "scavenger'd been looking for supplies in here, it seems.": "vypadá to, že mrchožrout zde čmuchal po zásobách.",
  "a shame to let what he'd found go to waste.": "byla by škoda zde nechat co našel.",
  "worth killing for, it seems.": "stálo za to ho zabít, zdá se.",
  "eye for an eye seems fair.": "oko za oko vypadá být fér.",
  "always worked before, at least.": "alespoň tomu tak vždy dříve bylo.",
  "picking the bones finds some useful trinkets.": "prohledání kostí přineslo pár užitečných drobností.",
  "some medicine abandoned in the drawers.": "pár léků zapomenutých v šuplících.",
  "the clinic has been ransacked.": "klinika byla vypleněna.",
  "only dust and stains remain.": "zbyl jen prach a špína.",
  "A Ruined City": "Zbořené město",
  "might be things worth having still inside.": "něco užitečného v něm stále může být.",
  "the towers of a decaying city dominate the skyline": "věže rozpadajícího se města dominují horizontu",
  "the streets are empty.": "ulice jsou prázdné.",
  "the air is filled with dust, driven relentlessly by the hard winds.": "vzduch je plný prachu, vířeného neúnavně burácejícími větry.",
  "leave city": "opusť město",
  "orange traffic cones are set across the street, faded and cracked.": "oranžové dopravní kužely jsou rozestavěny napříč ulicí, vybledlé a rozbité.",
  "lights flash through the alleys between buildings.": "světla poblikávají skrz průchody mezi budovami.",
  "a large shanty town sprawls across the streets.": "velká chudinská čtvrť se rozprostírá přes ulici.",
  "faces, darkened by soot and blood, stare out from crooked huts.": "tváře zčernalé sazemi a krví civí z pokřivených chatrčí.",
  "the shell of an abandoned hospital looms ahead.": "stěny opuštěné nemocnice se rýsují v dohledu.",
  "the old tower seems mostly intact.": "stará věž vypadá téměř nedotčeně.",
  "the shell of a burned out car blocks the entrance.": "karoserie vyhořelého auta blokuje vchod.",
  "most of the windows at ground level are busted anyway.": "většina oken v přízemí je vymlácená.",
  "a huge lizard scrambles up out of the darkness of an old metro station.": "obrovský ještěr se vyškrábal z temnoty staré stanice podzemní dráhy.",
  "descend": "sestup",
  "the shot echoes in the empty street.": "ozvěny výstřelů v prázdné ulici.",
  "the soldier steps out from between the buildings, rifle raised.": "voják vykročil z prostoru mezi budovami, pušku v pohotovosti.",
  "a frail man stands defiantly, blocking the path.": "křehký muž vzpurně blokuje cestu.",
  "nothing but downcast eyes.": "nic než sklopené oči.",
  "the people here were broken a long time ago.": "lidé zde byli zlomeni již dávno.",
  "empty corridors.": "prázdné uličky.",
  "the place has been swept clean by scavengers.": "místo bylo vyčištěno mrchožrouty.",
  "an old man bursts through a door, wielding a scalpel.": "starý muž se vřítil dveřmi oháněje se skalpelem.",
  "a thug is waiting on the other side of the wall.": "pobuda vyčkává za zdí.",
  "a snarling beast jumps out from behind a car.": "zuřivě vrčící šelma vyskočila zpoza auta.",
  "street above the subway platform is blown away.": "ulice nad nástupištěm podzemní dráhy je vymetená větrem.",
  "lets some light down into the dusty haze.": "propouští trochu světla dolů do prašného oparu.",
  "a sound comes from the tunnel, just ahead.": "zvuk přichází z tunelu, přímo vpředu.",
  "looks like a camp of sorts up ahead.": "vypadá to na nějaký druh tábora v dohledu.",
  "rusted chainlink is pulled across an alleyway.": "rezavý řetěz je natažen napříč průchodem.",
  "fires burn in the courtyard beyond.": "ohně hoří na dvorku na druhé straně.",
  "more voices can be heard ahead.": "více hlasů je slyšet zepředu.",
  "they must be here for a reason.": "musí tu být z nějakého důvodu.",
  "the sound of gunfire carries on the wind.": "vítr přináší zvuk střelby.",
  "the street ahead glows with firelight.": "ulice vepředu je ozářena ohněm.",
  "more squatters are crowding around now.": "nyní se shromáždilo více bezdomovců.",
  "someone throws a stone.": "někdo hodil kamenem.",
  "an improvised shop is set up on the sidewalk.": "improvizovaný obchod je zřízen na chodníku.",
  "the owner stands by, stoic.": "majitel nečinně přihlíží.",
  "strips of meat hang drying by the side of the street.": "sušící se plátky masa visí po straně ulice.",
  "the people back away, avoiding eye contact.": "lidé se stáhli, vyhýbajíce se očnímu kontaktu.",
  "someone has locked and barricaded the door to this operating theatre.": "někdo zamkl a zabarikádoval dveře do tohoto operačního sálu.",
  "a tribe of elderly squatters is camped out in this ward.": "kmen postarších bezdomovců je utábořen v tomto oddělení.",
  "a pack of lizards rounds the corner.": "tlupa ještěrů v bezprostřední blízkosti.",
  "strips of meat are hung up to dry in this ward.": "sušící se plátky masa visí v tomto oddělení.",
  "a large bird nests at the top of the stairs.": "velký pták hnízdí nahoře na schodech.",
  "the debris is denser here.": "sutin je zde více.",
  "maybe some useful stuff in the rubble.": "možná je v sutinách něco užitečného.",
  "a swarm of rats rushes up the tunnel.": "hejno krys se vyřítilo z tunelu.",
  "a large man attacks, waving a bayonet.": "velký muž útočí mávaje bajonetem.",
  "a second soldier opens fire.": "druhý voják zahájil palbu.",
  "a masked soldier rounds the corner, gun drawn": "maskovaný voják v bezprostřední blízkosti, zbraň vytaženou",
  "the crowd surges forward.": "banda se vrhla vpřed.",
  "a youth lashes out with a tree branch.": "mladík se ohání větví.",
  "a squatter stands firmly in the doorway of a small hut.": "bezdomovec stojí pevně zapřen ve dveřích malé chatrče.",
  "behind the door, a deformed figure awakes and attacks.": "deformovaná postava vyčkává za dveřmi a útočí.",
  "as soon as the door is open a little bit, hundreds of tentacles erupt.": "jakmile se dveře pootevřely, vyrojily se stovky chapadel.",
  "bird must have liked shiney things.": "pták musel mít rád lesklé věci.",
  "some good stuff woven into its nest.": "nějaký dobrý materiál je zapleten v jeho hnízdě.",
  "not much here.": "moc tu toho není.",
  "scavengers must have gotten to this place already.": "mrchožrouti se už sem museli dostat.",
  "the tunnel opens up at another platform.": "tunel ústí na další plošinu.",
  "the walls are scorched from an old battle.": "stěny jsou sežehnuté coby pozůstatek dávné bitvy.",
  "bodies and supplies from both sides litter the ground.": "těla a zásoby se povalují po zemi.",
  "the small military outpost is well supplied.": "malá vojenská základna je dobře zásobena.",
  "just as deadly now as they were then.": "nyní stejně smrtící jako byli oni tenkrát.",
  "searching the bodies yields a few supplies.": "prohledání těl přineslo trochu zásob.",
  "more soldiers will be on their way.": "vojáků tu bude asi víc.",
  "time to move on.": "je na čase zmizet.",
  "the small settlement has clearly been burning a while.": "v malé osadě zjevně před nedávnem hořelo.",
  "still time to rescue a few supplies.": "stále čas zachránit nějaké zásoby.",
  "there's not much, but some useful things can still be found.": "moc tu toho není, ale stále je možné najít něco užitečného.",
  "the young settler was carrying a canvas sack.": "mladý osadník má u sebe plátěný pytel.",
  "it contains travelling gear, and a few trinkets.": "obsahuje cestovní vybavení a pár cetek.",
  "there's nothing else here.": "nic jiného tu není.",
  "inside the hut, a child cries.": "uvnitř chýše pláče dítě.",
  "a few belongings rest against the walls.": "o zdi je opřeno pár věcí.",
  "the stench of rot and death fills the operating theatres.": "operační sál je naplněn puchem rozkladu a smrti.",
  "a few items are scattered on the ground.": "pár věcí je rozházeno po podlaze.",
  "there is nothing else here.": "nic jiného tu není.",
  "a pristine medicine cabinet at the end of a hallway.": "nedotčená skříňka s léky na konci chodby.",
  "the rest of the hospital is empty.": "zbytek nemocnice je prázdný.",
  "someone had been stockpiling loot here.": "někdo si zde schoval vše, co získal rabováním.",
  "the tentacular horror is defeated.": "chapadlovitý děs je poražen.",
  "inside, the remains of its victims are everywhere.": "pozůstatky jeho obětí jsou všudypřítomné.",
  "the warped man lies dead.": "zkroucený muž leží mrtev.",
  "the operating theatre has a lot of curious equipment.": "v operačním sále je spousta neobvyklého zařízení.",
  "the old man had a small cache of interesting items.": "starý muž měl malou skrýš se zajímavými předměty.",
  "An Old House": "Starý dům",
  "an old house remains here, once white siding yellowed and peeling.": "zbyl zde starý dům, kdysi bílá omítka je ohořelá a oprýskaná.",
  "the door hangs open.": "otevřené dveře visí volně v pantech.",
  "the remains of an old house stand as a monument to simpler times": "zbytky starého domu stojí jako připomínka lepších časů",
  "the house is abandoned, but not yet picked over.": "dům je opuštěn, ale ještě ne vyrabován.",
  "still a few drops of water in the old well.": "ve staré studni zbylo pár kapek vody.",
  "water replenished": "voda doplněna",
  "the house has been ransacked.": "dům byl vypleněn.",
  "but there is a cache of medicine under the floorboards.": "ale pod podlahou je skrýš s léky.",
  "a man charges down the hall, a rusty blade in his hand": "muž vrazil do chodby, v ruce rezavou čepel",
  "A Forgotten Battlefield": "Zapomenuté bojiště",
  "a battle was fought here, long ago.": "byla tu svedena bitva, dávno tomu.",
  "A Huge Borehole": "Obrovský vrt do země",
  "a huge hole is cut deep into the earth, evidence of the past harvest.": "obří díra je zaříznuta do země, důkaz dřívější těžby.",
  "they took what they came for, and left.": "vzali pro co přišli a odešli.",
  "A Crashed Ship": "Havarovaná loď",
  "lucky that the natives can't work the mechanisms.": "naštěstí domorodci nedokáží ovládat její ústrojí.",
  "with a little effort, it might fly again.": "s trochou úsilí, mohla by zase létat.",
  "salvage": "zachraň",
  "The Sulphur Mine": "Sirný důl",
  "the military is already set up at the mine's entrance.": "armáda je již připravena u vchodu do dolu.",
  "soldiers patrol the perimeter, rifles slung over their shoulders.": "vojáci hlídkují po obvodu, pušky přehozené přes rameno.",
  "a military perimeter is set up around the mine.": "kolem dolu je zřízeno vojenské ochranné území.",
  "attack": "zaútoč",
  "a soldier, alerted, opens fire.": "voják, varován, zahájil palbu.",
  "run": "uteč",
  "a second soldier joins the fight.": "druhý voják se přidal k boji.",
  "a grizzled soldier attacks, waving a bayonet.": "prošedivělý voják útočí mávaje bajonetem.",
  "the military presence has been cleared.": "přítomnost vojska byla eliminována.",
  "the mine is now safe for workers.": "důl je nyní bezpečný pro horníky.",
  "the sulphur mine is clear of dangers": "sirný důl je prost nebezpečí",
  "The Coal Mine": "Uhelný důl",
  "camp fires burn by the entrance to the mine.": "u vchodu do dolu hoří táborový oheň.",
  "men mill about, weapons at the ready.": "muži se poflakují okolo, zbraně připravené.",
  "this old mine is not abandoned": "tento starý důl není opuštěn",
  "a man joins the fight": "další muž se připojil k boji",
  "only the chief remains.": "zbyl pouze šéf.",
  "the camp is still, save for the crackling of the fires.": "tábor je klidný, bezpečný pro praskající ohně.",
  "the coal mine is clear of dangers": "uhelný důl je prost nebezpečí",
  "The Iron Mine": "Železný důl",
  "an old iron mine sits here, tools abandoned and left to rust.": "starý železný důl se zde rozprostírá, nástroje opuštěné a ponechány rzi.",
  "feral howls echo out of the darkness.": "tma vrací ozvěnou kvílení divočiny.",
  "the path leads to an abandoned mine": "stezka vede k opuštěnému dolu",
  "a large creature lunges, muscles rippling in the torchlight": "velká obluda se vrhla vpřed, svaly se jí napínají ve světle pochodně",
  "the beast is dead.": "šelma je mrtvá.",
  "the iron mine is clear of dangers": "železný důl je prost nebezpečí",
  "A Destroyed Village": "Zničená vesnice",
  "a destroyed village lies in the dust.": "zničená vesnice leží v prachu.",
  "charred bodies litter the ground.": "ohořelá těla pokrývají zem.",
  "the metallic tang of wanderer afterburner hangs in the air.": "kovový pach toho, co oheň zanechal z tuláků, visí ve vzduchu.",
  "a shack stands at the center of the village.": "uprostřed vesnice stojí chatrč.",
  "there are still supplies inside.": "uvnitř jsou stále zásoby.",
  "all the work of a previous generation is here.": "všechna práce předchozích generací je zde.",
  "ripe for the picking.": "škoda to tu nechat.",
  "saved.": "uloženo.",
  "wood": "dřevo",
  "builder": "stavitel",
  "teeth": "zuby",
  "meat": "maso",
  "fur": "kožešiny",
  "alien alloy": "mimozemská slitina",
  "bullets": "náboje",
  "charm": "talisman",
  "leather": "kůže",
  "iron": "železo",
  "steel": "ocel",
  "coal": "uhlí",
  "sulphur": "síra",
  "energy cell": "energetický článek",
  "torch": "pochodeň",
  "medicine": "léky",
  "hunter": "lovec",
  "trapper": "kladeč pastí",
  "tanner": "koželuh",
  "grenade": "granát",
  "bolas": "bolaso",
  "bayonet": "bajonet",
  "charcutier": "kuchař",
  "iron miner": "horník železa",
  "iron mine": "železný důl",
  "coal miner": "horník uhlí",
  "coal mine": "uhelný důl",
  "sulphur miner": "horník síry",
  "sulphur mine": "sirný důl",
  "armourer": "zbrojíř",
  "steelworker": "hutník",
  "bait": "návnady",
  "cured meat": "uzené maso",
  "scales": "šupiny",
  "compass": "kompas",
  "laser rifle": "laserová puška",
  "gatherer": "sběrač",
  "cloth": "plátno",
  "thieves": "zloději",
  "not enough fur": "není dost kožešiny",
  "not enough wood": "není dost dřeva",
  "not enough coal": "není dost uhlí",
  "not enough iron": "není dost železa",
  "not enough steel": "není dost oceli",
  "not enough sulphur": "není dost síry",
  "baited trap": "past s návnadou",
  "not enough scales": "není dost šupin",
  "not enough cloth": "není dost plátna",
  "not enough teeth": "není dost zubů",
  "not enough leather": "není dost kůže",
  "not enough meat": "není dost masa",
  "the compass points east": "kompas ukazuje na východ",
  "the compass points west": "kompas ukazuje na západ",
  "the compass points north": "kompas ukazuje na sever",
  "the compass points south": "kompas ukazuje na jih",
  "the compass points northeast": "kompas ukazuje na severovýchod",
  "the compass points northwest": "kompas ukazuje na severozápad",
  "the compass points southeast": "kompas ukazuje na jihovýchod",
  "the compass points southwest": "kompas ukazuje na jihozápad",
  "Outside": "Venku",
  "scraps of fur": "útržky kožešiny",
  "bits of meat": "kousky masa",
  "strange scales": "zvláštní šupiny",
  "scattered teeth": "roztroušené zuby",
  "tattered cloth": "rozedrané plátno",
  "a crudely made charm": "neuměle vyrobený talisman",
  "A Silent Forest": "Tichý les",
  "gather wood": "posbírej dřevo",
  "a stranger arrives in the night": "v noci přišel cizinec",
  "a weathered family takes up in one of the huts.": "zbídačená rodina se ubytovala v jedné z chýší.",
  "a small group arrives, all dust and bones.": "dorazila malá skupina, všichni kost a kůže.",
  "a convoy lurches in, equal parts worry and hope.": "přikodrcala se karavana, lidé plni obav i naděje.",
  "the town's booming. word does get around.": "vesnice se rozmáhá. zpráva o tom se šíří.",
  "pop ": "populace ",
  "forest": "les",
  "village": "vesnice",
  "check traps": "zkontroluj pasti",
  "A Lonely Hut": "Osamělá chýše",
  "A Tiny Village": "Malinká vesnička",
  "A Modest Village": "Skromná vesnička",
  "A Large Village": "Velká vesnice",
  "A Raucous Village": "Halasná vesnice",
  "the sky is grey and the wind blows relentlessly": "obloha je šedá a vítr vytrvale fičí",
  "dry brush and dead branches litter the forest floor": "suché chvojí a větve pokrývají zem v lese",
  "the traps contain ": "pasti obsahují ",
  "A Dusty Path": "Prašná cesta",
  "supplies:": "sebou:",
  "embark": "nalož a vyraž",
  "the compass points ": "kompas ukazuje na ",
  "perks:": "dovednosti:",
  "none": "nic",
  "armour": "brnění",
  "water": "voda",
  "free {0}/{1}": "volné místo {0}/{1}",
  "damage": "účinnost v boji",
  "weight": "váha",
  "available": "k dispozici",
  "trap": "past",
  "more traps to catch more creatures": "více pastí k chycení více zvířátek",
  "more traps won't help now": "více pastí už nepomůže",
  "cart": "vozík",
  "builder says she can make a cart for carrying wood": "stavitel říká, že umí vyrobit vozík pro přepravu dřeva",
  "the rickety cart will carry more wood from the forest": "vratký vozík přepraví více dřeva z lesa",
  "hut": "chýše",
  "builder says there are more wanderers. says they'll work, too.": "stavitel říká, že tuláků je více. říká také, že budou pracovat.",
  "builder puts up a hut, out in the forest. says word will get around.": "stavitel postavil chýši v lese. říká, že se to rozkřikne.",
  "no more room for huts.": "pro další chýše už není místo.",
  "lodge": "lovecká bouda",
  "villagers could help hunt, given the means": "vesničané mohou pomoci s lovem",
  "the hunting lodge stands in the forest, a ways out of town": "lovecká bouda stojí v lese, daleko od vesnice",
  "trading post": "tržiště",
  "a trading post would make commerce easier": "tržiště by usnadnilo obchod",
  "tannery": "koželužna",
  "builder says leather could be useful. says the villagers could make it.": "stavitel říká, že kůže by mohly být užitečné. říká, že vesničané by je mohli vyrábět.",
  "tannery goes up quick, on the edge of the village": "na okraji vesnice rychle roste koželužna",
  "smokehouse": "udírna",
  "builder finishes the smokehouse. she looks hungry.": "stavitel dokončuje udírnu. vypadá hladově",
  "workshop": "dílna",
  "builder says she could make finer things, if she had the tools": "stavitel říká, že by mohl vyrábět jemnější věci, pokud by měl nástroje",
  "workshop's finally ready. builder's excited to get to it": "dílna je konečně hotova. stavitel se nadšeně hrne dovnitř",
  "steelworks": "huť",
  "builder says the villagers could make steel, given the tools": "stavitel říká, že vesničané by mohli vyrábět ocel, pokud by k tomu měli nástroje",
  "a haze falls over the village as the steelworks fires up": "dým zahalil vesnici když ocelárna zahájila provoz",
  "armoury": "zbrojírna",
  "builder says it'd be useful to have a steady source of bullets": "stavitel říká, že by bylo užitečné mít stálý zdroj nábojů",
  "armoury's done, welcoming back the weapons of the past.": "zbrojírna je hotová, připravená na výrobu zbraní dávných časů.",
  "a torch to keep the dark away": "pochodeň k zažehnání temnoty",
  "waterskin": "měch na vodu",
  "this waterskin'll hold a bit of water, at least": "měch pojme aspoň trochu vody",
  "cask": "sud",
  "the cask holds enough water for longer expeditions": "sud pojme dost vody na delší výpravy",
  "water tank": "nádrž na vodu",
  "never go thirsty again": "dost bylo žízně jednou provždy",
  "bone spear": "kostěný oštěp",
  "this spear's not elegant, but it's pretty good at stabbing": "tento oštěp není zrovna elegantní, ale je velmi dobrý k bodání",
  "rucksack": "batoh",
  "carrying more means longer expeditions to the wilds": "možnost vzít více věcí znamená delší výpravy do divočiny",
  "wagon": "povoz",
  "the wagon can carry a lot of supplies": "povoz může přepravit spoustu zásob",
  "convoy": "karavana",
  "the convoy can haul mostly everything": "karavana může přepravit téměř cokoliv",
  "l armour": "l brnění",
  "leather's not strong. better than rags, though.": "kůže není pevná. ale pořád lepší než hadry",
  "i armour": "železné brnění",
  "iron's stronger than leather": "železo je pevnější než kůže",
  "s armour": "ocelové brnění",
  "steel's stronger than iron": "ocel je pevnější než železo",
  "iron sword": "železný meč",
  "sword is sharp. good protection out in the wilds.": "meč je ostrý. dobrá ochrana venku v divočině.",
  "steel sword": "ocelový meč",
  "the steel is strong, and the blade true.": "ocel je pevná a čepel poctivá.",
  "rifle": "puška",
  "black powder and bullets, like the old days.": "černý prach a kule, jak za starých časů.",
  "Room": "Místnost",
  "A Dark Room": "Místnost v tmách tonoucí",
  "light fire": "zažehni oheň",
  "stoke fire": "přilož",
  "the room is {0}": "místnost je {0}",
  "the fire is {0}": "oheň {0}",
  "freezing": "vymrzlá",
  "cold": "studená",
  "mild": "vlažná",
  "warm": "teplá",
  "hot": "vytopená",
  "dead": "nehoří",
  "smoldering": "doutná",
  "flickering": "poblikává",
  "burning": "hoří",
  "roaring": "divoce plane",
  "A Firelit Room": "Ohněm ozářená místnost",
  "not enough wood to get the fire going": "není dost dřeva k zapálení ohně",
  "the wood has run out": "dřevo došlo",
  "the light from the fire spills from the windows, out into the dark": "světlo ohně se rozlévá z oken do okolní tmy",
  "builder stokes the fire": "stavitel přiložil na oheň",
  "the wind howls outside": "venku skučí vítr",
  "the wood is running out": "dřevo dochází",
  "a ragged stranger stumbles through the door and collapses in the corner": "otrhaný cizinec vklopýtal do dveří a zhroutil se do rohu",
  "the stranger in the corner stops shivering. her breathing calms.": "cizinec v rohu se přestal třást, jeho dech se zklidnil.",
  "stores": "zásoby",
  "weapons": "zbraně",
  "total": "celkem",
  "not enough ": "nedostatečně ",
  "builder just shivers": "stavitel se jen třese",
  "build:": "postav:",
  "craft:": "vyrob:",
  "buy:": "kup:",
  "Ship": "Loď",
  "An Old Starship": "Stará kosmická loď",
  "hull:": "trup:",
  "engine:": "motor:",
  "reinforce hull": "vyztuž trup",
  "upgrade engine": "vylepši motor",
  "lift off": "zažehni motory", // odstartuj
  "not enough alien alloy": "není dost mimozemské slitiny",
  "Ready to Leave?": "Připraven vypadnout?",
  "time to get out of this place. won't be coming back.": "čas opustit tohle místo. jednou provždy.",
  "linger": "zůstaň",
  "hull: ": "trup: ",
  "Troposphere": "Troposféra",
  "Stratosphere": "Stratosféra",
  "Mesosphere": "Mezosféra",
  "Thermosphere": "Termosféra",
  "Exosphere": "Exosféra",
  "Space": "Vesmír",
  "score for this game: {0}": "skóre této hry: {0}",
  "total score: {0}": "celkové skóre: {0}",
  "iOS.": "iOS.",
  "android.": "android.",
  "punch": "udeř",
  "stab": "bodni",
  "swing": "máchni",
  "slash": "sekni mečem",
  "thrust": "zapíchni",
  "shoot": "střel",
  "blast": "odpal laser",
  "lob": "hoď granát",
  "tangle": "omrač",
  "An&nbsp;Outpost": "Základna",
  "Iron&nbsp;Mine": "Železný&nbsp;důl",
  "Coal&nbsp;Mine": "Uhelný&nbsp;důl",
  "Sulphur&nbsp;Mine": "Sirný&nbsp;důl",
  "An&nbsp;Old&nbsp;House": "Starý&nbsp;dům",
  "A&nbsp;Damp&nbsp;Cave": "Vlhká&nbsp;jeskyně",
  "An&nbsp;Abandoned&nbsp;Town": "Opuštěné&nbsp;město",
  "A&nbsp;Ruined&nbsp;City": "Zbořené&nbsp;město",
  "A&nbsp;Crashed&nbsp;Starship": "Havarovaná&nbsp;kosmická loď",
  "A&nbsp;Borehole": "Hluboký&nbsp;vrt",
  "A&nbsp;Battlefield": "Bitevní&nbsp;pole",
  "A&nbsp;Murky&nbsp;Swamp": "Kalná&nbsp;bažina",
  "A&nbsp;Destroyed&nbsp;Village": "Zničená&nbsp;vesnice",
  "water:{0}": "voda:{0}",
  "pockets": "kapsy",
  "hp: {0}/{1}": "síla úderu: {0}/{1}",
  "{0}:{1}": "{0}:{1}",
  "dangerous to be this far from the village without proper protection": "je nebezpečné být tak daleko od vesnice bez odpovídající ochrany",
  "safer here": "zde je bezpečněji",
  "the meat has run out": "maso došlo",
  "starvation sets in": "začíná hladovění",
  "there is no more water": "voda došla",
  "the thirst becomes unbearable": "žízeň se stává nesnesitelnou",
  "the trees yield to dry grass. the yellowed brush rustles in the wind.": "stromy ustoupily suché trávě. zežloutlý podrost šustí ve větru.",
  "the grasses thin. soon, only dust remains.": "traviny řídnou. brzy zůstane jen prach.",
  "the barrens break at a sea of dying grass, swaying in the arid breeze.": "vyprahlá pustina pozvolna přechází v moře usychající trávy, kolébající se v suchém vánku.",
  "Wanderer": "Tulák",
  "The&nbsp;Village": "Vesnice",
  "the world fades": "svět vybledl a ztratil se",
  "A Barren World": "Vyprahlý svět",
  "turning hyper mode speeds up the game to x2 speed. do you want to do that?": "zapnutí hyper módu zrychlí hru 2x. chceš to udělat?",
  "the point is made. in the next few days, the missing supplies are returned.": "výhružka zabrala. během pár dní byly zásoby zpět.",
  "a nomad shuffles into view, laden with makeshift bags bound with rough twine.": "přišoural se kočovník obtěžkaný pytli zavázanými hrubým motouzem.",
  "a bundle of sticks lies just beyond the threshold, wrapped in coarse furs.": "otep větví leží přímo  za prahem, ovinutá hrubými kožešinami.",
  "a wanderer arrives with an empty cart. says if he leaves with wood, he'll be back with more.": "objevil se tulák s prázdným vozíkem. říká, že pokud odejde se dřevem, vrátí se s více dřevem.",
  "a wanderer arrives with an empty cart. says if she leaves with furs, she'll be back with more.": "objevil se tulák s prázdným vozíkem. říká, že pokud odejde s kožešinami, vrátí se s více kožešinami.",
  "broken streetlights stand, rusting. light hasn't graced this place in a long time.": "rozbitá pouliční světla rezaví. světlo již dlouhý čas nezdobí toto místo.",
  "where the windows of the schoolhouse aren't shattered, they're blackened with soot.": "těch pár dosud neroztříštěných oken školní budovy je začerněno sazemi.",
  "it's been picked over by scavengers, but there's still some things worth taking.": "bylo to tu přehrabáno mrchožrouty, ale pořád zbylo pár věcí stojících za sebrání.",
  "a small basket of food is hidden under a park bench, with a note attached.": "malý košík jídla je ukryt pod parkovou lavičkou, s připojeným vzkazem.",
  "beneath the wanderer's rags, clutched in one of its many hands, a glint of steel.": "pod tulákovými hadry, záblesk ocele v jedné z mnoha rukou.",
  "a battered highway sign stands guard at the entrance to this once-great city.": "rozmlácená silniční značka stráží u vstupu do tohoto kdysi úžasného města.",
  "the towers that haven't crumbled jut from the landscape like the ribcage of some ancient beast.": "ty z věží, které se ještě nestihly rozdrolit, trčí z krajiny jako žebra nějaké dávné nestvůry.",
  "arms and munitions, relics from the war, are neatly arranged on the store-room floor.": "zbraně a munice, pozůstatky války, jsou úhledně naaranžovány na podlaze skladiště.",
  "the bodies of the wanderers that lived here are still visible in the flames.": "těla tuláků, kteří zde žili, jsou stále vidět v plamenech.",
  "the remaining settlers flee from the violence, their belongings forgotten.": "zbývající osadníci uprchli před násilím, zanechaje to svoje věci.",
  "battered technology from both sides lays dormant on the blasted landscape.": "otřískaná technika obou stran leží nečinně v měsíční krajině.",
  "castoff from the mammoth drills can still be found by the edges of the precipice.": "zbytky mamutích vrtáků jsou stále k vidění na okrajích srázu.",
  "the familiar curves of a wanderer vessel rise up out of the dust and ash. ": "povědomé křivky tulákovy lodi vyrůstají z prachu a popela. ",
  "bleached bones are strewn about the entrance. many, deeply scored with jagged grooves.": "vybledlé kosti pokrývají okolí vchodu. mnohé s hlubokými zubatými rýhami.",
  "builder says she can make traps to catch any creatures might still be alive out there": "stavitel říká, že umí vyrobit pasti k chytání zvířátek, která mohou být stále naživu někde venku",
  "now the nomads have a place to set up shop, they might stick around a while": "nyní mají kočovníci místo k obchodování, mohou se chvíli zdržet",
  "should cure the meat, or it'll spoil. builder says she can fix something up.": "maso by se mělo konzervovat, jinak se zkazí. stavitel říká, že to může zařídit.",
  "the stranger is standing by the fire. she says she can help. says she builds things.": "cizinec se postavil vedle ohně. říká, že může pomoci, že staví různé věci.",
  "the stranger shivers, and mumbles quietly. her words are unintelligible.": "cizinec se třese a tiše mumlá. jeho slova jsou nesrozumitelná.",
  "somewhere above the debris cloud, the wanderer fleet hovers. been on this rock too long.": "někde nad haldou trosek se vznáší tulákova flotila. byl na tomto kusu země příliš dlouho.",
  "expanded story. alternate ending. behind the scenes commentary. get the app.": "rozšířený příběh. jiný konec. postřehy zpoza scény. získej aplikaci.",
  "the trees are gone. parched earth and blowing dust are poor replacements.": "stromy zmizely. vyprahlá zem a oblaka vířícího prachu jsou chudou náhradou.",
  "trees loom on the horizon. grasses gradually yield to a forest floor of dry branches and fallen leaves.": "stromy se hrozivě tyčí na horizontu. traviny postupně ustupují lesnímu podrostu se suchými větvemi a popadaným listím.",
  "a wall of gnarled trees rises from the dust. their branches twist into a skeletal canopy overhead.": "stěna pokroucených stromů se zdvihá z prachu. jejich větve nad hlavou splétají klenbu připomínající kostru.",
  "restores": "obnovuje",
  "hp": "sil úderu",
  "use with rifle": "do pušky",
  "use with laser rifle": "do laserové pušky",
  "The Shady Builder": "Pochybný stavitel",
  "a shady builder passes through": "okolo prochází pochybný stavitel",
  "says he can build you a hut for less wood": "říká, že umí postavit chýši s použitím méně dřeva",
  "300 wood": "dej 300",
  "the shady builder has made off with your wood": "pochybný stavitel spěšně zmizel i se dřevem",
  "the shady builder builds a hut": "pochybný stavitel postavil chýši"
});
